function normalize_brain (patient_folder, x_fname, lesion_fname, file_format, atlas_name, is_crt. temp_op, heal_op, smooth_op, fraq)
%warp.norm.brain <- function (patient.folder, p.fname, lesion.fname, file.format = 'nii', atlas.name = 'AAL', is.ct = TRUE, temp.op = "scct", heal.op = TRUE, smooth.op = 1.5){
pfolder = quote(win2lin([patient_folder,'\'],'full'));
xfname = quote(win2lin(x_fname));
lesfname = quote(win2lin(lesion_fname));
fileformat = quote(file_format);
atlasname = quote(atlas_name);
isct = num2str(is_ct);
tempop = quote(temp_op);
healop = num2str(heal_op);
smoothop = num2str(smooth_op);
deskullop = num2str(0); %turns auto-deskull off, since this step requires eyeballing
frq = num2str(fraq);
Rpipe('warp.norm.brain', ...
    pfolder, ...
    xfname, ...
    lesfname, ...
    fileformat, ...
    atlasname, ...
    isct, ...
    tempop, ...
    healop, ...
    smoothop, ...
    deskullop, ...
    frq, ...
    alignment_op);
end